eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
spring.main.web-application-type=reactive
spring.application.name=gateway-service
server.port=8222

# Enable discovery locator
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Route for Chambre Service
spring.cloud.gateway.routes[0].id=chambre
spring.cloud.gateway.routes[0].uri=lb://CHAMBRE
spring.cloud.gateway.routes[0].predicates[0]=Path=/chambres/**

## Route for Chambre Service
#spring.cloud.gateway.routes[1].id=chambre
#spring.cloud.gateway.routes[1].uri=lb://CHAMBRE
#spring.cloud.gateway.routes[1].predicates[1]=Path=/chambres/**


# Optional: Config server
spring.config.import=optional:configserver:http://localhost:9999